### ISSUE TITLE
counter change when time get's adjusted 

### ISSUE THREAD

**Issue by Nokius** [AsteroidOS/asteroid-stopwatch#1]
When traveled I noticed that the stopwatch counter added the amount of time which is the differences between the timezones I travled.

I started the stopwatch in CEST and changed during the flight to EEST the stopwatch added then 1 hour.

**Comment by FlorentRevest** [comment]
I will see what we can do with timed.

Thanks for reporting!

**Comment by FlorentRevest** [comment]
I just checked the behavior of jolla-clock on my SFOS phone and the same bug is observed. SailfishOS also uses the difference between two Date() calls which results in the counter being wrong on hour-change. It means that there doesn't seem to be a way we can use timed to avoid the problem you met. I'll close the issue since it is very rarely met and isn't a very problematic bug.
(thanks for reporting and sorry for the very long delay!)
